apiVersion: v1
kind: Service

metadata:
  name: redis

spec:
  selector:
    app.kubernetes.io/component: redis

  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
---
apiVersion: v1
kind: Service

metadata:
  name: redis-sentinel

spec:
  type: NodePort

  selector:
    app.kubernetes.io/component: sentinel

  ports:
    - name: sentinel
      port: 26379
      targetPort: sentinel
      {{- if .Values.sentinel.nodePort }}
      nodePort: {{ .Values.sentinel.nodePort }}
      {{- end }}
