apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: redis

spec:
  serviceName: redis

  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      containers:
        - name: redis

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: IfNotPresent

          args:
            - --requirepass
            - $(REDIS_PASSWORD)

          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: password

          ports:
            - name: redis
              containerPort: 6379

          resources:
{{ toYaml .Values.resources | indent 12 }}

          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
          {{- end }}

  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: {{ .Values.persistence.size }}

  {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  {{- end }}
