apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nebo-redis-dev
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 20.6.3

    helm:
      values: |
        architecture: standalone

        auth:
          enabled: true
          password: dev-password

        master:
          persistence:
            enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: nebo-redis-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true