apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NurZaRio/company.git
    targetRevision: main
    path: projects
    directory:
      recurse: true
      include: '{nebo/redis,programmatic/redis}'
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true