apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: redis-applications
  namespace: argocd

spec:
  generators:
    - git:
        repoURL: https://github.com/NurZaRio/company.git
        revision: main

        directories:
          - path: projects/*/redis/*

  template:
    metadata:
      name: '{{path[1]}}-redis-{{path.basename}}'

    spec:
      project: default

      source:
        repoURL: https://github.com/NurZaRio/company.git
        targetRevision: main
        path: '{{path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}-redis-{{path.basename}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true