image:
  repository: redis
  tag: "7.2"

service:
  port: 6379

sentinel:
  port: 26379
  quorum: 2
  downAfterMilliseconds: 5000
  failoverTimeout: 10000
  parallelSyncs: 1

auth:
  enabled: true
  password: changeme

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""

replicaCount: 3
