apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: redis-commander
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - project: tools

  template:
    metadata:
      name: redis-commander

    spec:
      project: default

      source:
        repoURL: https://github.com/NurZaRio/company.git
        targetRevision: main
        path: infrastructure/redis-commander

      destination:
        server: https://kubernetes.default.svc
        namespace: redis-commander

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
