image:
  repository: ghcr.io/joeferner/redis-commander
  tag: latest

service:
  type: NodePort
  port: 8081
  nodePort: 30081

redisConnections:
  - name: nebo-dev
    host: redis.nebo-redis-dev.svc.cluster.local
    port: 6379
    password: nebo-dev-password
  - name: nebo-stage
    host: redis.nebo-redis-stage.svc.cluster.local
    port: 6379
    password: nebo-stage-password
  - name: programmatic-dev
    host: redis.programmatic-redis-dev.svc.cluster.local
    port: 6379
    password: programmatic-dev-password
  - name: programmatic-stage
    host: redis.programmatic-redis-stage.svc.cluster.local
    port: 6379
    password: programmatic-stage-password
