image:
  repository: ghcr.io/joeferner/redis-commander
  tag: latest

service:
  type: NodePort
  port: 8081
  nodePort: 30081

redisConnections:
  - name: nebo-dev
    host: redis.nebo-redis-dev.svc.cluster.local
    port: 6379
    password: nebo-dev-password
  - name: nebo-prod
    host: redis.nebo-redis-prod.svc.cluster.local
    port: 6379
    password: nebo-prod-password
  - name: programmatic-dev
    host: redis.programmatic-redis-dev.svc.cluster.local
    port: 6379
    password: programmatic-dev-password
  - name: programmatic-prod
    host: redis.programmatic-redis-prod.svc.cluster.local
    port: 6379
    password: programmatic-prod-password
