image:
  repository: redis
  tag: "7.2"

auth:
  enabled: true
  password: "SUPER-PROD-PASSWORD"

service:
  port: 6379

resources:
  requests:
    cpu: 500m
    memory: 512Mi

  limits:
    cpu: "1"
    memory: 1Gi

persistence:
  enabled: true
  size: 20Gi